/**
 * Zero-dependency fluid-LP solver for two-budget admission (joint-LP policy).
 *
 * Solves the deterministic (fluid) relaxation of the revenue-management
 * admission problem and returns the **bid prices** (LP dual variables) that drive
 * the joint-LP filter in {@link unifiedAdmission}:
 *
 * ```
 * max   Σ wᵢ vᵢ xᵢ
 * s.t.  Σ wᵢ xᵢ      ≤ R        (rate budget,  dual p_R ≥ 0)
 *       Σ wᵢ cᵢ xᵢ   ≤ C        (cost budget,  dual p_C ≥ 0)
 *       0 ≤ xᵢ ≤ 1
 * ```
 *
 * By LP duality / complementary slackness the optimal admission rule is the
 * **bid-price test**: admit a request of type `i` iff `vᵢ ≥ p_R + p_C·cᵢ`.
 *
 * Strict zero-runtime-deps ⇒ no LP library. With only two budget constraints the
 * optimal vertex has **at most two fractional** types (one per tight constraint);
 * the rest are fully admitted or fully rejected. We enumerate the four binding
 * regimes — neither / rate-only / cost-only / both — over the candidate marginal
 * type(s), solve the small linear system that makes the tight constraint(s)
 * exact, and keep the feasible candidate with the best objective. The duals come
 * from complementary slackness on the binding constraint(s).
 *
 * This generalizes the 2-type reference implementation in
 * `research/bigger-bets/unified/sim.ts` (TK-1007) to N types; the math (vertex
 * enumeration + complementary-slackness duals) is unchanged — see THEORY.md and
 * `research/bigger-bets/joint-lp-admission/DESIGN.md` §3–§4 (D-JLP-7). Correctness
 * is pinned by `test/admission/fluid-lp.test.ts` (the THEORY fixture) and a
 * KKT-certificate property test (every returned solution is primal-feasible and
 * satisfies dual feasibility + complementary slackness, which together certify LP
 * optimality without an external solver).
 *
 * @packageDocumentation
 */

import { ThrottleKitError } from "../core/errors";

/** One request archetype in the workload model handed to {@link solveFluidLp}. */
export interface WorkloadType {
  /** Cost-axis weight per admit (matches `Limiter.check(key, cost)`'s 2nd arg). */
  cost: number;
  /** Business value of admitting one (revenue, priority, …). */
  value: number;
  /** Arrival weight / probability. Need not sum to 1 — used as-is as the per-type usage scale. */
  weight: number;
}

/** Input to {@link solveFluidLp}: the workload mixture plus the two budgets. */
export interface FluidLpInput {
  /** The request archetypes. Non-empty. */
  types: WorkloadType[];
  /** Rate budget R per window (admits/window). > 0. */
  rateBudget: number;
  /** Cost budget C per window (cost units/window). > 0. */
  costBudget: number;
}

/** Output of {@link solveFluidLp}: the bid prices, the optimal admit plan, and its value. */
export interface FluidLpSolution {
  /** Bid prices (LP duals). Admit type i iff `value ≥ duals.rate + duals.cost · cost`. */
  duals: { rate: number; cost: number };
  /** Optimal admit fraction per input type (same order as `input.types`). */
  admitFractions: number[];
  /** Optimal objective `Σ wᵢ vᵢ xᵢ` (telemetry / tests). */
  objective: number;
}

/** Bound-feasibility / equality tolerances (mirrors the sim.ts reference). */
const BOUND_TOL = 1e-9;
const TIGHT_TOL = 1e-7;

/** A fully-specified candidate vertex: an admit plan, its duals, and its objective. */
interface Candidate {
  x: number[];
  rate: number;
  cost: number;
  objective: number;
}

/**
 * Solve the 2-budget fluid LP and return the bid prices, optimal admit plan, and
 * objective. O(types²) — hand-written vertex enumeration, zero dependencies.
 *
 * @throws ThrottleKitError if `types` is empty, any `cost`/`value`/`weight` is
 *   non-finite or negative, or either budget is non-finite or ≤ 0.
 */
export function solveFluidLp(input: FluidLpInput): FluidLpSolution {
  const { types, rateBudget: R, costBudget: C } = input;
  validate(input);

  const n = types.length;
  const w = types.map((t) => t.weight);
  const v = types.map((t) => t.value);
  const c = types.map((t) => t.cost);

  const candidates: Candidate[] = [];

  // Clamp an admit plan into [0,1] and record it iff budget-feasible (within
  // tolerance). Clamping — rather than rejecting a value a hair over a bound —
  // keeps the boundary case where slack budget should fully admit a type. Every
  // recorded candidate is verified feasible on its clamped values, so the
  // objective is never overstated; the true optimum is always generated by some
  // regime below, so it is never lost either.
  const consider = (x: number[]): void => {
    let rate = 0;
    let cost = 0;
    let objective = 0;
    for (let i = 0; i < n; i++) {
      const clamped = Math.max(0, Math.min(1, x[i] as number));
      x[i] = clamped;
      rate += w[i]! * clamped;
      cost += w[i]! * c[i]! * clamped;
      objective += w[i]! * v[i]! * clamped;
    }
    if (rate > R + TIGHT_TOL || cost > C + TIGHT_TOL) return; // budget-infeasible
    candidates.push({ x: x.slice(), rate, cost, objective });
  };

  const indices = Array.from({ length: n }, (_, i) => i);

  // ── Regime "neither binds": admit everything. ──────────────────────────────
  consider(new Array<number>(n).fill(1));

  // ── Regime "rate binds only": rate-usage and objective both scale by wᵢ, so
  //    value-per-rate-unit = vᵢ ⇒ greedily admit by DESCENDING value until the
  //    rate budget is spent (the last partial type fractional). Greedy is exact
  //    for a single constraint and cascades leftover budget across ties and
  //    successive types. If the plan violates cost, consider() drops it and the
  //    both-bind regime covers that optimum. ──────────────────────────────────
  {
    const order = [...indices].sort((a, b) => v[b]! - v[a]!);
    const x = new Array<number>(n).fill(0);
    let rem = R;
    for (const i of order) {
      const need = w[i]!;
      if (need <= BOUND_TOL) {
        x[i] = 1; // zero-weight: free on the rate axis
      } else if (rem >= need) {
        x[i] = 1;
        rem -= need;
      } else {
        x[i] = rem / need; // fractional (0 once the budget is spent)
        rem = 0;
      }
    }
    consider(x);
  }

  // ── Regime "cost binds only": value-per-cost-unit = vᵢ/cᵢ (density) ⇒ greedily
  //    admit by DESCENDING density (cost-free types first) until the cost budget
  //    is spent. Same greedy-optimality + cascade as the rate regime. ──────────
  {
    const density = (i: number): number =>
      c[i]! > BOUND_TOL ? v[i]! / c[i]! : Number.POSITIVE_INFINITY;
    const order = [...indices].sort((a, b) => density(b) - density(a));
    const x = new Array<number>(n).fill(0);
    let rem = C;
    for (const i of order) {
      const need = w[i]! * c[i]!;
      if (need <= BOUND_TOL) {
        x[i] = 1; // cost-free (or zero-weight): free on the cost axis
      } else if (rem >= need) {
        x[i] = 1;
        rem -= need;
      } else {
        x[i] = rem / need;
        rem = 0;
      }
    }
    consider(x);
  }

  // ── Regime "both bind": exactly two fractional types (m, k) with c_m ≠ c_k.
  //    Duals from the 2×2 {vₘ = p_R + p_C·cₘ ; v_k = p_R + p_C·c_k}; classify the
  //    others by reduced value; solve the two tight budgets for (xₘ, x_k). ──────
  for (let m = 0; m < n; m++) {
    for (let k = m + 1; k < n; k++) {
      const dc = c[k]! - c[m]!;
      if (Math.abs(dc) <= BOUND_TOL) continue; // singular: same cost ⇒ no 2×2 dual
      const pC = (v[k]! - v[m]!) / dc;
      const pR = v[m]! - pC * c[m]!;
      if (pR < -BOUND_TOL || pC < -BOUND_TOL) continue;
      const x = new Array<number>(n).fill(0);
      let forcedRate = 0;
      let forcedCost = 0;
      for (let i = 0; i < n; i++) {
        if (i === m || i === k) continue;
        if (v[i]! - pR - pC * c[i]! > TIGHT_TOL) {
          x[i] = 1;
          forcedRate += w[i]!;
          forcedCost += w[i]! * c[i]!;
        }
      }
      // Solve: w_m·x_m + w_k·x_k = R − forcedRate ; w_m·c_m·x_m + w_k·c_k·x_k = C − forcedCost
      const a11 = w[m]!;
      const a12 = w[k]!;
      const a21 = w[m]! * c[m]!;
      const a22 = w[k]! * c[k]!;
      const det = a11 * a22 - a12 * a21; // = w_m·w_k·(c_k − c_m)
      if (Math.abs(det) <= BOUND_TOL) continue;
      const b1 = R - forcedRate;
      const b2 = C - forcedCost;
      x[m] = (b1 * a22 - a12 * b2) / det;
      x[k] = (a11 * b2 - b1 * a21) / det;
      consider(x);
    }
  }

  // Pick the feasible candidate with the greatest objective (LP optimum). The
  // all-reject plan x = 0 is always feasible, so a best always exists.
  let best: Candidate = { x: new Array<number>(n).fill(0), rate: 0, cost: 0, objective: 0 };
  for (const cand of candidates) {
    if (cand.objective > best.objective + BOUND_TOL) best = cand;
  }

  const duals = recoverDuals(best, v, c, R, C);
  return { duals, admitFractions: best.x, objective: best.objective };
}

/** Reduced-value significance threshold for KKT classification in dual recovery. */
const DUAL_TOL = 1e-7;
/** Slack tolerance for "budget tight" / "fraction saturated" in dual recovery. */
const SLACK_TOL = 1e-6;

/**
 * Bid prices (LP duals) for the chosen optimal plan, by **enumerate-and-verify**:
 * try every structural dual candidate — (0,0); each single-axis threshold
 * `(vᵢ, 0)` and `(0, vᵢ/cᵢ)`; and each two-type 2×2 solution — and return the
 * first that satisfies the KKT predicate against the plan (dual feasibility +
 * complementary slackness + reduced-value sign ↔ admit fraction). For an optimal
 * plan a valid dual always exists and is in this candidate set, so a
 * verified-correct dual is returned; the `{0,0}` fallback covers the
 * neither-binds plan. The accepted dual passes the same KKT certificate the test
 * asserts — by construction, and with tighter tolerances than the test, so what
 * is returned here always clears it.
 */
function recoverDuals(
  best: Candidate,
  v: number[],
  c: number[],
  R: number,
  C: number,
): { rate: number; cost: number } {
  const n = best.x.length;
  const rateTight = Math.abs(best.rate - R) <= SLACK_TOL;
  const costTight = Math.abs(best.cost - C) <= SLACK_TOL;

  /** Does (pR, pC) satisfy the KKT certificate against `best`? */
  const valid = (pR: number, pC: number): boolean => {
    if (pR < -DUAL_TOL || pC < -DUAL_TOL) return false; // dual feasibility
    if (pR > DUAL_TOL && !rateTight) return false; // complementary slackness (rate)
    if (pC > DUAL_TOL && !costTight) return false; // complementary slackness (cost)
    for (let i = 0; i < n; i++) {
      const reduced = v[i]! - pR - pC * c[i]!;
      const xi = best.x[i] as number;
      if (reduced > DUAL_TOL && xi < 1 - SLACK_TOL) return false; // should be fully admitted
      if (reduced < -DUAL_TOL && xi > SLACK_TOL) return false; // should be rejected
    }
    return true;
  };

  const accept = (pR: number, pC: number): { rate: number; cost: number } => ({
    rate: Math.max(0, pR),
    cost: Math.max(0, pC),
  });

  if (valid(0, 0)) return accept(0, 0);
  for (let i = 0; i < n; i++) {
    if (valid(v[i]!, 0)) return accept(v[i]!, 0);
  }
  for (let i = 0; i < n; i++) {
    if (c[i]! > BOUND_TOL && valid(0, v[i]! / c[i]!)) return accept(0, v[i]! / c[i]!);
  }
  for (let m = 0; m < n; m++) {
    for (let k = m + 1; k < n; k++) {
      const dc = c[k]! - c[m]!;
      if (Math.abs(dc) <= BOUND_TOL) continue;
      const pC = (v[k]! - v[m]!) / dc;
      const pR = v[m]! - pC * c[m]!;
      if (valid(pR, pC)) return accept(pR, pC);
    }
  }
  return { rate: 0, cost: 0 };
}

function validate(input: FluidLpInput): void {
  const { types, rateBudget, costBudget } = input;
  if (!Array.isArray(types) || types.length === 0) {
    throw new ThrottleKitError("solveFluidLp: `types` must be a non-empty array");
  }
  for (let i = 0; i < types.length; i++) {
    const t = types[i] as WorkloadType;
    for (const [field, value] of [
      ["cost", t.cost],
      ["value", t.value],
      ["weight", t.weight],
    ] as const) {
      if (typeof value !== "number" || !Number.isFinite(value) || value < 0) {
        throw new ThrottleKitError(
          `solveFluidLp: types[${i}].${field} must be a finite number ≥ 0 (got ${String(value)})`,
        );
      }
    }
  }
  for (const [field, value] of [
    ["rateBudget", rateBudget],
    ["costBudget", costBudget],
  ] as const) {
    if (typeof value !== "number" || !Number.isFinite(value) || value <= 0) {
      throw new ThrottleKitError(
        `solveFluidLp: ${field} must be a finite number > 0 (got ${String(value)})`,
      );
    }
  }
}
